// Generated by LiveScript 1.2.0
(function(){
  var App;
  App = (function(){
    App.displayName = 'App';
    var prototype = App.prototype, constructor = App;
    function App(){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    return App;
  }());
  module.exports = App;
}).call(this);
