// Generated by LiveScript 1.2.0
(function(){
  var dom;
  dom = function(){
    return dom.find.apply(this, arguments);
  };
  dom.qwery = require('qwery');
  dom.find = dom.qwery;
  dom.select = dom.qwery;
  dom.ready = require('domready');
  dom.walk = require('dom-walk');
  dom.become = require('become');
  dom.bean = require('bean');
  dom.on = dom.bean.on;
  dom.one = dom.bean.one;
  dom.off = dom.bean.off;
  dom.fire = dom.bean.fire;
  dom.bean.setSelectorEngine(dom.qwery);
  dom.atts = require('atts');
  dom.attr = dom.atts.attr;
  dom.removeAttr = dom.atts.removeAttr;
  dom.toggleAttr = dom.atts.toggleAttr;
  dom.hasAttr = dom.atts.hasAttr;
  dom.attrs = dom.atts.anyAttr;
  dom.ancestors = require('ancestors');
  dom.parents = dom.ancestors;
  dom.alignit = require('alignit');
  dom.domCreate = require('dom-create');
  dom.create = dom.domCreate;
  dom.live = require('./live-dom');
  dom.ready(function(){
    return require('dom-shim');
  });
  module.exports = dom;
}).call(this);
