// Generated by LiveScript 1.2.0
(function(){
  var App, skelly;
  App = require('./app');
  skelly = function(){
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args), t;
      return (t = typeof result)  == "object" || t == "function" ? result || child : child;
  })(App, arguments, function(){});
  };
  module.exports = skelly;
}).call(this);
